import { type BlcssRule } from "./types.ts";

/** Emit standard CSS from parsed BlcssRule[] */
export function emitCSS(rules: BlcssRule[]): string {
  const lines: string[] = [
    `/* Generated by booLangCSS compiler */`,
    `/* Source: .blcss → Linear A IR → VMC → CSS */`,
    ``,
  ];

  for (const rule of rules) {
    lines.push(`${rule.selector} {`);
    for (const d of rule.decls) {
      lines.push(`  ${d.property}: ${d.resolvedCSS};`);
    }
    lines.push(`}`);
    lines.push(``);
  }

  return lines.join("\n");
}
