import { type CSSDecl, type LinearAToken } from "./types.ts";
import { type SignMap } from "./sign_map.ts";
import { SIGN_STATES, VALID_TRANSITIONS, FSM_THRESHOLD } from "../../spec/linear-a-fsm-validator.ts";

/** Emit a Linear A token for one CSS declaration */
export function emitToken(decl: CSSDecl, signMap: SignMap): LinearAToken {
  const onsetSign = signMap.propertyToSign.get(decl.property) ?? signMap.allSigns[0].sign;
  const bodySign  = signMap.bodySign;

  // Determine CODA sign from CSS unit if present
  const unitMatch = decl.resolvedCSS.match(/(px|em|%|rem|vh|vw|pt)$/);
  const unit      = unitMatch ? unitMatch[1] : "";
  const codaSign  = signMap.unitToSign.get(unit)
    ?? signMap.allSigns.find(s => s.positionBias === "CODA")?.sign
    ?? signMap.allSigns[0]?.sign
    ?? "𐘽";

  const group = `${onsetSign}.${bodySign}.${codaSign}`;

  const fromState = SIGN_STATES.get(onsetSign) ?? "MIXED";
  const toState   = SIGN_STATES.get(codaSign)  ?? "MIXED";
  const transition = `${fromState}→${toState}`;
  const valid = VALID_TRANSITIONS.has(transition);

  return { group, fromState, toState, transition, valid, cssDecl: decl };
}

/** Emit all Linear A tokens for a list of CSS declarations */
export function emitTokens(decls: CSSDecl[], signMap: SignMap): LinearAToken[] {
  return decls.map(d => emitToken(d, signMap));
}

/** Compute FSM score for a sequence of tokens (proportion valid) */
export function computeFsmScore(tokens: LinearAToken[]): number {
  if (tokens.length === 0) return 0;
  const valid = tokens.filter(t => t.valid).length;
  return valid / tokens.length;
}

/** Format Linear A tokens as .linearA file content */
export function formatLinearAIR(tokens: LinearAToken[], selector: string): string {
  const lines = [
    `# booLangCSS Linear A IR — ${selector}`,
    `# Generated by src/boolangcss/linear_a_ir.ts`,
    ``,
  ];
  for (const t of tokens) {
    lines.push(`${t.group}    # ${t.cssDecl.property}: ${t.cssDecl.resolvedCSS}  [${t.transition}${t.valid ? " ✓" : " ✗"}]`);
  }
  const score = computeFsmScore(tokens);
  lines.push(``, `# FSM score: ${score.toFixed(4)} (threshold: ${FSM_THRESHOLD.toFixed(4)})`);
  return lines.join("\n");
}
