/**
 * vmc_emitter.ts — Voynich Machine Code emitter for booLangCSS.
 *
 * VMC instruction set (Voynich EVA morphology):
 *   chedy  <canonical_byte>   — open rule block (selector hash)
 *   chey                     — close rule block
 *   daiin  <prop> <val...>   — property declaration
 *   dal    <byte>            — reset to canonical ground
 *   shedy  <n> <p>           — keyframe at light-length state
 *   qokaiin                  — specificity validation gate
 *   dain   <name> <val>      — variable bind
 *   dy                       — no-op / end of stream
 *
 * Data payload: canonical byte from canonicalOctet(compactIndex).
 * A VMC file reads like Voynich manuscript text when printed in EVA font.
 */
import { canonicalOctet } from "../../../booLang-hardening/canonical_octet.ts";
import { nonceToBij6, bij6ToBase36 } from "../../../booLang-hardening/bij6.ts";
import { type LinearAToken, type VMCInstruction } from "./types.ts";
import { type SignMap } from "./sign_map.ts";

function signToCanonicalByte(sign: string, signMap: SignMap): number {
  const entry = signMap.allSigns.find(s => s.sign === sign);
  const idx   = entry?.compactIndex ?? 1;
  return canonicalOctet(idx > 255 ? idx % 256 : idx);
}

/** Emit VMC instructions for a selector (open block) */
export function emitBlockOpen(selector: string, _signMap: SignMap): VMCInstruction {
  const bytes: number[] = [];
  for (let i = 0; i < Math.min(selector.length, 3); i++) {
    bytes.push(canonicalOctet(selector.charCodeAt(i) & 0xFF));
  }
  return { opcode: "chedy", args: bytes, comment: `rule block: ${selector}` };
}

/** Emit VMC instruction for closing a rule block */
export function emitBlockClose(): VMCInstruction {
  return { opcode: "chey", args: [], comment: "close rule block" };
}

/** Emit VMC instruction for one Linear A token */
export function emitDeclInstruction(token: LinearAToken, signMap: SignMap): VMCInstruction {
  const signs = token.group.split(".");
  const args  = signs.map(s => signToCanonicalByte(s, signMap));
  return {
    opcode:  "daiin",
    args,
    comment: `${token.cssDecl.property}: ${token.cssDecl.resolvedCSS}`,
  };
}

function formatInstr(i: VMCInstruction): string {
  const argsStr = i.args.length > 0
    ? i.args.map(a => String(a).padStart(3)).join(" ")
    : "";
  const bij6s = i.args.map(a => bij6ToBase36(nonceToBij6(a))).join(",");
  return `${i.opcode.padEnd(10)} ${argsStr.padEnd(15)} ; ${i.comment}  [bij6: ${bij6s || "—"}]`;
}

/** Format VMC instructions as .vmc file content */
export function formatVMC(
  blockOpen: VMCInstruction,
  tokens: LinearAToken[],
  signMap: SignMap,
): string {
  const lines = [
    `; booLangCSS VMC — Voynich Machine Code`,
    `; Generated by src/boolangcss/vmc_emitter.ts`,
    `; Each instruction: <eva_opcode> <canonical_byte>...  ; comment`,
    ``,
    formatInstr(blockOpen),
  ];

  for (const t of tokens) {
    lines.push(formatInstr(emitDeclInstruction(t, signMap)));
  }

  lines.push(formatInstr(emitBlockClose()));
  lines.push(`dy                          ; end of stream`);

  return lines.join("\n");
}
