/* blid_lock.h — AUTO-GENERATED by blid-voynich-lock.ts. DO NOT EDIT.
 * BLID identity anchor for booLang Voynich-lowered SHA-256 implementation.
 * Mode: full (includes genesis BLID)
 * Voynich master:
 *   cho.lch.che.dai.edy.ota.kai.kai.oke.she.kai.iin
 */
#ifndef BLID_LOCK_H
#define BLID_LOCK_H

#define BLID_LOCK_VERSION 1

static const unsigned char BLID_LOCK_MASTER[32] = {
    0x3b, 0x14, 0xc5, 0xaa, 0x62, 0xaf, 0xe6, 0xa4, 0x55, 0xb8, 0xc0, 0x6c, 0x0e, 0x8a, 0x53, 0x98,
    0x49, 0x04, 0x65, 0x89, 0xcc, 0x84, 0x7f, 0x8b, 0x89, 0x96, 0x22, 0xd4, 0xc8, 0xbd, 0xd6, 0x8c
};

static const unsigned char BLID_LOCK_HASH12[6] = {
    0x3b, 0x14, 0xc5, 0xaa, 0x62, 0xaf
};

static const char BLID_LOCK_VOYNICH[] =
    "cho.lch.che.dai.edy.ota.kai.kai.oke.she.kai.iin";

#endif /* BLID_LOCK_H */
