/* blid_lock_standalone.h — AUTO-GENERATED by blid-voynich-lock.ts. DO NOT EDIT.
 * BLID identity anchor for booLang Voynich-lowered SHA-256 implementation.
 * Mode: standalone (no genesis)
 * Voynich master:
 *   iin.edy.aii.eed.lch.oke.eed.edy.iin.dai.aii.hed
 */
#ifndef BLID_LOCK_STANDALONE_H
#define BLID_LOCK_STANDALONE_H

#define BLID_LOCK_STANDALONE_VERSION 1

static const unsigned char BLID_LOCK_STANDALONE_MASTER[32] = {
    0xfc, 0x8e, 0xb6, 0xec, 0xf4, 0x87, 0x25, 0x06, 0xbe, 0xd7, 0xff, 0x4d, 0xc6, 0x2e, 0x9e, 0x56,
    0x28, 0x21, 0x61, 0xc8, 0xac, 0x31, 0x23, 0x5c, 0x79, 0x32, 0x42, 0x4d, 0x11, 0x05, 0xa1, 0x2b
};

static const unsigned char BLID_LOCK_STANDALONE_HASH12[6] = {
    0xfc, 0x8e, 0xb6, 0xec, 0xf4, 0x87
};

static const char BLID_LOCK_STANDALONE_VOYNICH[] =
    "iin.edy.aii.eed.lch.oke.eed.edy.iin.dai.aii.hed";

#endif /* BLID_LOCK_STANDALONE_H */
